### ISSUE TITLE
Ref Error Override causes Crash

### ISSUE THREAD

**Issue by Blkx-Darkreaper** [nhmkdev/cardmaker#146] opened 2024-04-09 21:14 UTC
It appears that having a ref error in a google sheet causes the application to crash when that ref error is read as part of a card's override

**Comment by nhmkdev** [comment] 2024-04-10 01:48
I attempted to reproduce this with a ref error (mine was due to a cycle in a `sum`) and nothing broke. What is the ref error that caused the issue for you?

**Comment by Blkx-Darkreaper** [comment] 2024-04-10 15:23
Ref error that caused the crash. It doesn't happen on the first card that has the error, but rather the second that the program tries to open
```
=Concatenate("Times New Roman;", ROUND($AD3*#REF!,0), ";1;0;0;0")
```

![image](https://github.com/nhmkdev/cardmaker/assets/8000312/62a05eaa-bfe2-445e-b1db-fd412c236aa3)

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at CardMaker.Card.DrawFormattedText.Draw(Graphics zGraphics, Deck zDeck, ProjectLayoutElement zElement, String sInput)
   at CardMaker.Card.Render.TypeElementRenderProcessor.Render(Graphics zGraphics, ProjectLayoutElement zElement, Deck zDeck, String sInput, Int32 nX, Int32 nY, Boolean bExport)
   at CardMaker.Card.CardRenderer.DrawElement(Graphics zGraphics, Deck zDeck, ProjectLayoutElement zElement, Int32 nX, Int32 nY, String sInput, Boolean bExport)
   at CardMaker.Card.CardRenderer.DrawCard(Int32 nX, Int32 nY, Graphics zGraphics, DeckLine zDeckLine, Boolean bExport, Boolean bDrawBackground)
   at CardMaker.Card.CardCanvas.OnPaint(PaintEventArgs e)
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.UserControl.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9232.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
CardMaker
    Assembly Version: 1.3.0.0
    Win32 Version: 1.3.0.0
    CodeBase: file:///P:/Cardmaker/v1300/CardMaker.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9236.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
PdfSharp-gdi
    Assembly Version: 1.50.5147.0
    Win32 Version: 1.50.5147.0
    CodeBase: file:///P:/Cardmaker/v1300/PdfSharp-gdi.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9236.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Google.Apis.Sheets.v4
    Assembly Version: 1.57.0.2727
    Win32 Version: 1.57.0.2727
    CodeBase: file:///P:/Cardmaker/v1300/Google.Apis.Sheets.v4.DLL
----------------------------------------
Google.Apis
    Assembly Version: 1.57.0.0
    Win32 Version: 1.57.0.0
    CodeBase: file:///P:/Cardmaker/v1300/Google.Apis.DLL
----------------------------------------
Google.Apis.Core
    Assembly Version: 1.57.0.0
    Win32 Version: 1.57.0.0
    CodeBase: file:///P:/Cardmaker/v1300/Google.Apis.Core.DLL
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Google.Apis.Drive.v3
    Assembly Version: 1.57.0.2789
    Win32 Version: 1.57.0.2789
    CodeBase: file:///P:/Cardmaker/v1300/Google.Apis.Drive.v3.DLL
----------------------------------------
Google.Apis.Auth
    Assembly Version: 1.57.0.0
    Win32 Version: 1.57.0.0
    CodeBase: file:///P:/Cardmaker/v1300/Google.Apis.Auth.DLL
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 13.0.0.0
    Win32 Version: 13.0.1.25517
    CodeBase: file:///P:/Cardmaker/v1300/Newtonsoft.Json.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9236.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9214.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

**Comment by nhmkdev** [comment] 2024-04-11 03:56
Thanks for all the detail on this one! 👍  It helped me track the issue down. FormattedText elements can run into an issue with a font override that is bad so now it will at least default even if the override doesn't apply a correct font. https://github.com/nhmkdev/cardmaker/commit/7d6e77265426cb4c5fa492e873af816a1a62e7c2

This fix will be included in the next pre-release build.

**Closed by nhmkdev** 2024-04-11 03:56 UTC
