### ISSUE TITLE
Crash when selecting element

### ISSUE THREAD

**Issue by daniel--** [nhmkdev/cardmaker#19] opened 2016-03-10 20:11 UTC
I am experiencing a crash when selecting an element from the Canvas after editing an element in the Element Control window.

To reproduce:

Select an element and edit a property such as vertical alignment.

Immediately, (without selecting anything else or activating any other windows) right click on an element in the canvas to select it.

Result:

A broken window with title 'save' and appears and the program no longer responds and must be killed.

Backtrace:

`System.ArgumentOutOfRangeException: ControlCollection does not have that many controls
Parameter name: index
Actual value was 0.
  at System.Windows.Forms.Control+ControlCollection.get_Item (Int32 index) <0x40b06730 + 0x0018f> in <filename unknown>:0 
  at System.Windows.Forms.TabControl.GetTab (Int32 index) <0x40b9b000 + 0x00032> in <filename unknown>:0 
  at (wrapper remoting-invoke-with-check) System.Windows.Forms.TabControl:GetTab (int)
  at System.Windows.Forms.TabControl+TabPageCollection.get_Item (Int32 index) <0x40b9ae40 + 0x00023> in <filename unknown>:0 
  at System.Windows.Forms.TabControl.get_SelectedTab () <0x40b9ae00 + 0x00034> in <filename unknown>:0 
  at System.Windows.Forms.TabControl.OnLeave (System.EventArgs e) <0x40d95dd0 + 0x00017> in <filename unknown>:0 
  at System.Windows.Forms.Control.FireLeave () <0x40c562b0 + 0x0001e> in <filename unknown>:0 
  at System.Windows.Forms.ContainerControl.set_ActiveControl (System.Windows.Forms.Control value) <0x40b6e8f0 + 0x0021c> in <filename unknown>:0 
  at System.Windows.Forms.Control.Select (Boolean directed, Boolean forward) <0x40bb6310 + 0x000d6> in <filename unknown>:0 
  at System.Windows.Forms.Control.SelectNextControl (System.Windows.Forms.Control ctl, Boolean forward, Boolean tabStopOnly, Boolean nested, Boolean wrap) <0x40b6d1c0 + 0x00216> in <filename unknown>:0 
  at System.Windows.Forms.ContainerControl.ChildControlRemoved (System.Windows.Forms.Control control) <0x40d04ab0 + 0x001b3> in <filename unknown>:0 
  at (wrapper remoting-invoke-with-check) System.Windows.Forms.ContainerControl:ChildControlRemoved (System.Windows.Forms.Control)
  at System.Windows.Forms.Control+ControlCollection.Remove (System.Windows.Forms.Control value) <0x40bc1e70 + 0x00107> in <filename unknown>:0 
  at System.Windows.Forms.TabControl+ControlCollection.Remove (System.Windows.Forms.Control value) <0x40d043f0 + 0x001eb> in <filename unknown>:0 
  at System.Windows.Forms.Control+ControlCollection.Clear () <0x40d04280 + 0x000fa> in <filename unknown>:0 
  at System.Windows.Forms.TabControl+TabPageCollection.Clear () <0x40d04230 + 0x00027> in <filename unknown>:0 
  at CardMaker.Forms.MDIElementControl.HandleTypeEnableStates () <0x40d01920 + 0x00113> in <filename unknown>:0 
  at CardMaker.Forms.MDIElementControl.Element_Selected (System.Object sender, CardMaker.Events.Args.ElementEventArgs args) <0x40bd5830 + 0x00083> in <filename unknown>:0 
  at (wrapper delegate-invoke) <Module>:invoke_void_object_ElementEventArgs (object,CardMaker.Events.Args.ElementEventArgs)
  at CardMaker.Events.Managers.ElementManager.FireElementSelectedEvent (System.Collections.Generic.List`1 listElements) <0x40bd5610 + 0x000bc> in <filename unknown>:0 
  at CardMaker.Forms.MDILayoutControl.listViewElements_SelectedIndexChanged (System.Object sender, System.EventArgs e) <0x40cfff10 + 0x00137> in <filename unknown>:0 
  at System.Windows.Forms.ListView.OnSelectedIndexChanged (System.EventArgs e) <0x40cd1520 + 0x00065> in <filename unknown>:0 
  at System.Windows.Forms.ListView.OnSelectedIndexChanged () <0x40cd0620 + 0x0002a> in <filename unknown>:0 
  at (wrapper remoting-invoke-with-check) System.Windows.Forms.ListView:OnSelectedIndexChanged ()
  at System.Windows.Forms.ListViewItem.SetSelectedCore (Boolean value) <0x40cd02c0 + 0x0017f> in <filename unknown>:0 
  at System.Windows.Forms.ListViewItem.set_Selected (Boolean value) <0x40cd0260 + 0x00047> in <filename unknown>:0 
  at CardMaker.Forms.MDILayoutControl.ChangeSelectedElement (System.String sName) <0x40d3a0e0 + 0x00067> in <filename unknown>:0 
  at CardMaker.Forms.MDILayoutControl.Element_Selected (System.Object sender, CardMaker.Events.Args.ElementEventArgs args) <0x40d3a040 + 0x0007f> in <filename unknown>:0 
  at CardMaker.Events.Managers.ElementManager.FireElementSelectRequestedEvent (CardMaker.XML.ProjectLayoutElement zElement) <0x40d39d60 + 0x00067> in <filename unknown>:0 
  at CardMaker.Forms.MDICanvas.contextmenuClick_Handler (System.Object sender, System.EventArgs e) <0x40d39b60 + 0x000f7> in <filename unknown>:0 
  at CardMaker.Forms.MDICanvas.contextmenuOpening_Handler (System.Object sender, System.ComponentModel.CancelEventArgs e) <0x40d39550 + 0x0034b> in <filename unknown>:0 
  at System.Windows.Forms.ToolStripDropDown.OnOpening (System.ComponentModel.CancelEventArgs e) <0x40c8d6a0 + 0x00065> in <filename unknown>:0 
  at System.Windows.Forms.ToolStripDropDown.Show (Point position, ToolStripDropDownDirection direction) <0x40c8ca90 + 0x007bc> in <filename unknown>:0 
  at System.Windows.Forms.ToolStripDropDown.Show (System.Windows.Forms.Control control, Point position) <0x40d39480 + 0x0008b> in <filename unknown>:0 
  at (wrapper remoting-invoke-with-check) System.Windows.Forms.ToolStripDropDown:Show (System.Windows.Forms.Control,System.Drawing.Point)
  at System.Windows.Forms.Control.WmContextMenu (System.Windows.Forms.Message& m) <0x40d38f80 + 0x002a3> in <filename unknown>:0 
  at System.Windows.Forms.Control.WndProc (System.Windows.Forms.Message& m) <0x40ad6570 + 0x002a7> in <filename unknown>:0 
  at System.Windows.Forms.ScrollableControl.WndProc (System.Windows.Forms.Message& m) <0x40b22980 + 0x00013> in <filename unknown>:0 
  at System.Windows.Forms.ContainerControl.WndProc (System.Windows.Forms.Message& m) <0x40b22900 + 0x0005b> in <filename unknown>:0 
  at System.Windows.Forms.UserControl.WndProc (System.Windows.Forms.Message& m) <0x40b69df0 + 0x0006b> in <filename unknown>:0 
  at System.Windows.Forms.Control+ControlWindowTarget.OnMessage (System.Windows.Forms.Message& m) <0x40ad6540 + 0x00024> in <filename unknown>:0 
  at System.Windows.Forms.Control+ControlNativeWindow.WndProc (System.Windows.Forms.Message& m) <0x40ad6500 + 0x00036> in <filename unknown>:0 
  at System.Windows.Forms.NativeWindow.WndProc (IntPtr hWnd, Msg msg, IntPtr wParam, IntPtr lParam) <0x40ad4e40 + 0x0031c> in <filename unknown>:0 
System.ArgumentOutOfRangeException: ControlCollection does not have that many controls
Parameter name: index
Actual value was 0.
  at System.Windows.Forms.Control+ControlCollection.get_Item (Int32 index) <0x40b06730 + 0x0018f> in <filename unknown>:0 
  at System.Windows.Forms.TabControl.GetTab (Int32 index) <0x40b9b000 + 0x00032> in <filename unknown>:0 
  at System.Windows.Forms.TabControl.GetTabRect (Int32 index) <0x40d02630 + 0x0001b> in <filename unknown>:0 
  at (wrapper remoting-invoke-with-check) System.Windows.Forms.TabControl:GetTabRect (int)
  at System.Windows.Forms.Theming.Default.TabControlPainter.Draw (System.Drawing.Graphics dc, Rectangle area, System.Windows.Forms.TabControl tab) <0x40d01de0 + 0x002c7> in <filename unknown>:0 
  at System.Windows.Forms.ThemeWin32Classic.DrawTabControl (System.Drawing.Graphics dc, Rectangle area, System.Windows.Forms.TabControl tab) <0x40d01d90 + 0x00048> in <filename unknown>:0 
  at System.Windows.Forms.TabControl.Draw (System.Drawing.Graphics dc, Rectangle clip) <0x40d01d40 + 0x0003d> in <filename unknown>:0 
  at System.Windows.Forms.TabControl.OnPaintInternal (System.Windows.Forms.PaintEventArgs pe) <0x40d01cc0 + 0x0005b> in <filename unknown>:0 
  at System.Windows.Forms.Control.WmPaint (System.Windows.Forms.Message& m) <0x40c459f0 + 0x00140> in <filename unknown>:0 
  at System.Windows.Forms.Control.WndProc (System.Windows.Forms.Message& m) <0x40ad6570 + 0x001f7> in <filename unknown>:0 
  at System.Windows.Forms.TabControl.WndProc (System.Windows.Forms.Message& m) <0x40b9acd0 + 0x000d3> in <filename unknown>:0 
  at System.Windows.Forms.Control+ControlWindowTarget.OnMessage (System.Windows.Forms.Message& m) <0x40ad6540 + 0x00024> in <filename unknown>:0 
  at System.Windows.Forms.Control+ControlNativeWindow.WndProc (System.Windows.Forms.Message& m) <0x40ad6500 + 0x00036> in <filename unknown>:0 
  at System.Windows.Forms.NativeWindow.WndProc (IntPtr hWnd, Msg msg, IntPtr wParam, IntPtr lParam) <0x40ad4e40 + 0x0031c> in <filename unknown>:0`

**Comment by nhmkdev** [comment] 2016-03-11 04:35
I was unable to reproduce the crash. Though I think I may be able to with a couple more details. I suspect the element you have selected initially is a different type then the one you are attempting to select (based on the mention of the tab control). I tried a mix of Elements (Text, FormattedText, Shape, and Graphic).

Can you provide details on the two elements in question? (any various settings you can specify will hopefully help me trigger the same error)

Also just to double check: What version of CardMaker are you running? What OS are you running in?

Thanks!

**Comment by daniel--** [comment] 2016-03-11 04:44
I am actually able to reproduce this with a single element. Precise Steps.

1. Open Card Maker
2. Select Default Layout
3. Add element in 'layout control'
4. Set H Alignment to Center
5. Immediately left click element on Canvas

I am running Card Maker Beta 0.99.4.0[UNSTABLE] V.A4 on Linux Mint 17.2 Cinnamon 64-bit

**Comment by nhmkdev** [comment] 2016-03-12 02:51
Ah mono issues... I am sure there are tons of little things like this due to differences in the .NET implementation. I'll see if I can add in some mono specific hacks to avoid this.

**Comment by daniel--** [comment] 2016-03-13 18:06
Thanks for looking into this, if there is anything else I can do to help out let me know.

**Comment by nhmkdev** [comment] 2016-03-13 22:37
I need to get my ubuntu virtual machine rebuilt. I hope to look into these ubuntu issues in the next few days (or sooner!).

**Comment by nhmkdev** [comment] 2016-03-17 03:27
This should be resolved with build: [v.0.99.4.0-unstable.v.a5](https://github.com/nhmkdev/cardmaker/releases/tag/v.0.99.4.0-unstable.v.a5)

**Closed by nhmkdev** 2016-03-17 03:27 UTC
Labels: bug
