### ISSUE TITLE
FormattedText: When images don't fit in row height, they turn to horizontal lines

### ISSUE THREAD

**Issue by kek444** [nhmkdev/cardmaker#35] opened 2017-03-27 19:35 UTC
https://i.imgur.com/z036OaL.png

^There should be two inline icons with -1 in the scrshot

The issue appears when:

1.) The script is JavaScript

and either

2.a) image is larger than line height and a percentage factor in img tag is used (setting e.g. percentage = 0.9 doesn't work)

or

2.b) img is defined with fixed height and width, but the FormattedText element is smaller than the set height

**Comment by nhmkdev** [comment] 2017-03-28 03:39
I have definitely seen this before with inline images. The horizontal lines you are seeing generally indicate that the content is larger than the bounds of the element (not necessarily 100% accurate though!).

Can you supply a couple of extra details to help me investigate the issue:

Which version of CardMaker are you running and in which OS?
What is the width/height of the element?
What is the Line Spacing value set to for the element?
What is the width/height of the image you are trying to place in-line?

Does any percentage value work for the img tag?

Thanks!

**Comment by kek444** [comment] 2017-03-28 07:09
- the bug is consistently present since 0.99.3 (don't know before that), win 10
- in this case, the image is .png 96x96 with transparency, and I can't get it to show up at any percentage (so i use explicit height and width, but that prevents me from using variable aspect ratios)
- height of element is 120 currently, but the problem is the same however I enlarge it (it seems to depend on the first constraint it comes across, in this case line height)
- line spacing is default (14)

**Comment by nhmkdev** [comment] 2017-03-28 14:29
Is this only with JavaScript or can you reproduce the same issue using the Incept translation?

If possible could you attach/link the image giving you trouble? I'm guessing other images run into the same problem.

I had a few minutes and I tried making my own 96x96 png with a transparent background and verified it was appearing correctly (with Incept, not JavaScript though). I tried in win7/win10. I'll try JS this evening.

...and one final weird possibility: What font are you using?

**Comment by kek444** [comment] 2017-03-28 17:00
I've found something interesting.

The same project shows up ok on my work pc. The same loaded project, the same across all fonts.
It's just my home pc that has this problem.

Windows 10 in both cases.
Any companion libraries (MS maybe) that could be the cause?

**Comment by nhmkdev** [comment] 2017-03-29 00:48
Wile guess... but it's possible it's the version of the .NET framework.

**Comment by kek444** [comment] 2017-03-29 07:43
I have the latest visual studio on both PCs, no difference in framework versions.. :/

Any recommendation I can perhaps try in the way of runtime debugging?

**Comment by nhmkdev** [comment] 2017-03-29 13:47
If I was able to repro it I would see what is happening with all the evaluation in the ImageMarkup.cs file in the ProcessMarkup method. The TargetRect should be going through a couple of reassignments as it works through what the final rectangle will be. In particular I would take a look at the before and after of line 115. The issue might be elsewhere though.

Before that line it should just be the width/height of your image. After that line it should be the scaled version.

..... annnnnd it looks like the font height might be driving the height of the result ..... I put the wrong information in the manual (line spacing is only for newlines). This likely means that the font you are using is likely resulting in a height calculation that is incorrect. Is the font on both machines the exact same version of the given font?

Thanks for all the help in tracking this down and improving the quality of the app/documentation!

**Comment by kek444** [comment] 2017-03-29 14:18
The issue is somehow only on my home pc, it's the same in all fonts, from times new roman to comic sans (and the custom Hultog font I like the most for prototyping). I simply can't get percentage to work.

Tried changing font size from 12 to 56 etc., it's the same.

Glad to help, card maker is a very handy tool, and I especially like the extra features that JavaScript enables.

**Comment by nhmkdev** [comment] 2017-03-30 01:02
I'm definitely curious what the application thinks your font height is on your home PC. I'll continue to explore assuming that is the issue. Something certainly is suspect with the way the .NET framework is reporting font height (and maybe width).

One overly complex (and waaaaay over the top) solution is to try running  a virtual machine to run CardMaker at home (I use VirtualBox to try ubuntu, win7, win10 when testing sometimes).

**Comment by nhmkdev** [comment] 2017-03-31 03:41
The changes related to this issue should be resolved in [v.0.99.4.0-unstable.v.a17](https://github.com/nhmkdev/cardmaker/releases/tag/v.0.99.4.0-unstable.v.a17).

Thanks! Let me know if you run into any further issues related to '.' vs. ','

**Closed by nhmkdev** 2017-03-31 03:41 UTC
Labels: bug
